# Generated by Django 6.0.1 on 2026-02-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
